#!/bin/sh
if [ $1 -ge 51 ] || [ $1 -le 255 ]; then
	for file in $(find /sys/devices/platform -type f -name 'pwm[0-9]*_enable'); do
		echo '1' | sudo tee "$file"
	done
	for file in $(find /sys/devices/platform -type f -name 'pwm[0-9]'); do
		echo "$1" | sudo tee "$file"
	done
fi
