#!/bin/sh
pkg_temp='coretemp'
files=$(find /sys/devices/platform -type f -name 'name')
for file in $files; do
	if grep -qF "$pkg_temp" "$file"; then
		echo "#define CPU_TEMP_FILE \"$file\"" | sed 's/name/temp1_input/'
		exit
	fi
done
echo "getcpufile: $pkg_temp not found. in $files!"
echo 'Need to manually add CPU_TEMP_FILE macro to cpu.generated.h.'
echo 'Example cpu.generated.h:'
echo '#define CPU_TEMP_FILE "/path/to/cpu_temp'
exit 1
